#ifndef JNL_FORM_ANALYZE_GLOBAL_H
#define JNL_FORM_ANALYZE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JNL_FORM_ANALYZE_LIBRARY)
#  define JNL_FORM_ANALYZESHARED_EXPORT Q_DECL_EXPORT
#else
#  define JNL_FORM_ANALYZESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JNL_FORM_ANALYZE_GLOBAL_H
