#ifndef TRACETESTDLL_GLOBAL_H
#define TRACETESTDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRACETESTDLL_LIBRARY)
#  define TRACETESTDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRACETESTDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACETESTDLL_GLOBAL_H
